name: C Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc-9, gcc-10, clang]
        exclude:
          # Exclude combinations that don't work on macOS
          - os: macos-latest
            compiler: gcc-9
          - os: macos-latest
            compiler: gcc-10

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config libncurses-dev check ${{ matrix.compiler }}
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake pkg-config ncurses check
    
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Test
      run: |
        cd build
        CTEST_OUTPUT_ON_FAILURE=1 make test
