name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS (x64)
            os: macos-12
            artifact_suffix: macOS-x64
          - name: macOS (ARM64)
            os: macos-latest
            artifact_suffix: macOS-arm64

          - name: Ubuntu (x64)
            os: ubuntu-latest
            artifact_suffix: Linux-Ubuntu-x64
          - name: Ubuntu (ARM64)
            os: ubuntu-latest
            artifact_suffix: Linux-Ubuntu-arm64
            arch: aarch64

          - name: Fedora (x64)
            os: ubuntu-latest
            container: fedora:latest
            artifact_suffix: Linux-Fedora-x64
            
          - name: Arch (x64)
            os: ubuntu-latest
            container: archlinux:latest
            artifact_suffix: Linux-Arch-x64

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM build
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Build Project
        run: |
          set -e # Exit immediately if a command fails
          chmod +x build.sh

          if [ "${{ matrix.arch }}" == "aarch64" ]; then
            docker run --rm -v ${{ github.workspace }}:/ws --workdir=/ws \
              arm64v8/ubuntu:22.04 \
              ./build.sh
          else
            ./build.sh
          fi

      - name: Prepare Release Artifacts
        run: |
          mkdir release_package
          cp build/bin/sce release_package/
          cp README.md LICENSE CONTRIBUTING.md release_package/
          tar -czvf sce-${{ github.ref_name }}-${{ matrix.artifact_suffix }}.tar.gz -C release_package .

      - name: Create/Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: sce-${{ github.ref_name }}-