name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            artifact_suffix: macOS
          - name: Ubuntu
            os: ubuntu-latest
            artifact_suffix: Linux-Ubuntu
          - name: Fedora
            os: ubuntu-latest
            container: fedora:latest
            artifact_suffix: Linux-Fedora
          - name: Arch
            os: ubuntu-latest
            container: archlinux:latest
            artifact_suffix: Linux-Arch

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (Fedora)
        if: matrix.container == 'fedora:latest'
        run: dnf install -y make cmake gcc gcc-c++ pkg-config ncurses-devel check-devel git

      - name: Install Dependencies (Arch)
        if: matrix.container == 'archlinux:latest'
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed base-devel cmake pkg-config ncurses check git

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Build Project
        run: ./build.sh

      - name: Prepare Release Artifacts
        run: |
          mkdir release_package
          cp build/bin/sce release_package/
          cp README.md LICENSE CONTRIBUTING.md release_package/
          tar -czvf sce-${{ github.ref_name }}-${{ matrix.artifact_suffix }}.tar.gz -C release_package .

      - name: Create/Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: sce-${{ github.ref_name }}-${{ matrix.artifact_suffix }}.tar.gz